---
- name: Installing oh-my-zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "~/.oh-my-zsh"
    update: yes
  register: macos_ohmyzsh_git_result
  changed_when: "macos_ohmyzsh_git_result.after|default('after') != macos_ohmyzsh_git_result.before|default('before')"

- name: Setting default shell
  become: true
  shell: "chsh -s $(which zsh) {{ ansible_ssh_user }}"
  when: macos_ohmyzsh.default

- name: Configuring oh-my-zsh
  template:
    src: ".zshrc.j2"
    dest: "~/.zshrc"
    backup: yes
  when: macos_ohmyzsh.configure